user_name = input('Введите имя пользователя')
print("Приветствую вас " + user_name )
title = input('Введите заголовок')
print(title)
content = input('Введите описание вашей заметки')
print(content)
status = input('Введите статус заметки')
print(status)
created_date = input('Введите дату создания заметки \'в формате дд.мм\'')
print(created_date)
issue_date = input('Введите планируемую дату окончания заметки  \'в формате дд.мм\'')
print(issue_date)