user_name = ('Ivan')
title = ('Заголовок')
content = ('Описание')
status = ('В работе')
created_date = ('24-12-2024')
issue_date = ('25-12-2024')
print(user_name , ('Ivan'))
print(title , ('Заголовок'))
print(content , ('Описание'))
print(status ,('В работе'))
print(created_date , ('24-12-2024'))
print(issue_date , ('25-12-2024'))